Repository zarrs/zarrs, pull requests merged in 2025-06, with the labels that each got.

#202 feat: add `Complex{BFloat16,Float16,Float32,Float64}` data types
  CHANGELOG.md
  Cargo.toml
  zarrs/doc/status/data_types.md
  zarrs/src/array/codec/array_to_array/bitround.rs
  zarrs/src/array/codec/array_to_array/bitround/bitround_codec.rs
  zarrs/src/array/codec/array_to_array/bitround/bitround_partial_decoder.rs
  zarrs/src/array/codec/array_to_array/fixedscaleoffset/fixedscaleoffset_codec.rs
  zarrs/src/array/codec/array_to_bytes/pcodec.rs
  zarrs/src/array/codec/array_to_bytes/pcodec/pcodec_codec.rs
  zarrs/src/array/codec/array_to_bytes/pcodec/pcodec_partial_decoder.rs
  zarrs/src/array/data_type.rs
  zarrs_data_type/Cargo.toml
  zarrs_registry/Cargo.toml
Labels: enhancement

#207 Support `null` fill values for v2 arrays
  zarrs/tests/data/v2_fill_value.py
  zarrs/tests/data/v2_str0.py
  zarrs/tests/data/zarr_python_compat/bool_v2_fv_null.zarr/.zarray
  zarrs/tests/data/zarr_python_compat/bool_v2_fv_null.zarr/.zattrs
  zarrs/tests/data/zarr_python_compat/bool_v2_fv_null.zarr/0
  zarrs/tests/data/zarr_python_compat/float_v2_fv_null.zarr/.zarray
  zarrs/tests/data/zarr_python_compat/float_v2_fv_null.zarr/.zattrs
  zarrs/tests/data/zarr_python_compat/float_v2_fv_null.zarr/0
  zarrs/tests/data/zarr_python_compat/int_v2_fv_null.zarr/.zarray
  zarrs/tests/data/zarr_python_compat/int_v2_fv_null.zarr/.zattrs
  zarrs/tests/data/zarr_python_compat/int_v2_fv_null.zarr/0
  zarrs/tests/zarr_python.rs
  zarrs_metadata/src/v2/array.rs
  zarrs_metadata_ext/src/v2_to_v3.rs
Labels: breaking-changes, compatibility

#214 refactor!: improve `ArrayBuilder` and `{Array,Chunk}Representation` API
  CHANGELOG.md
  zarrs/benches/array_blosc.rs
  zarrs/benches/array_uncompressed.rs
  zarrs/benches/codecs.rs
  zarrs/examples/array_write_read.rs
  zarrs/examples/array_write_read_ndarray.rs
  zarrs/examples/array_write_read_string.rs
  zarrs/examples/async_array_write_read.rs
  zarrs/examples/custom_data_type_fixed_size.rs
  zarrs/examples/custom_data_type_float8_e3m4.rs
  zarrs/examples/custom_data_type_uint12.rs
  zarrs/examples/custom_data_type_uint4.rs
  zarrs/examples/custom_data_type_variable_size.rs
  zarrs/examples/rectangular_array_write_read.rs
  zarrs/examples/sharded_array_write_read.rs
  zarrs/examples/zip_array_write_read.rs
  zarrs/src/array.rs
  zarrs/src/array/array_async_sharded_readable_ext.rs
  zarrs/src/array/array_builder.rs
  zarrs/src/array/array_builder/array_builder_chunk_grid.rs
  zarrs/src/array/array_builder/array_builder_data_type.rs
  zarrs/src/array/array_builder/array_builder_fill_value.rs
  zarrs/src/array/array_dlpack_ext.rs
  zarrs/src/array/array_errors.rs
  zarrs/src/array/array_representation.rs
  zarrs/src/array/array_sync_sharded_readable_ext.rs
  zarrs/src/array/chunk_cache/chunk_cache_lru.rs
  zarrs/src/array/codec/array_to_array/bitround.rs
  zarrs/src/array/codec/array_to_array/fixedscaleoffset.rs
  zarrs/src/array/codec/array_to_array/squeeze.rs
  zarrs/src/array/codec/array_to_array/transpose.rs
  zarrs/src/array/codec/array_to_bytes/bytes.rs
  zarrs/src/array/codec/array_to_bytes/codec_chain.rs
  zarrs/src/array/codec/array_to_bytes/packbits.rs
  zarrs/src/array/codec/array_to_bytes/pcodec.rs
  zarrs/src/array/codec/array_to_bytes/sharding.rs
  zarrs/src/array/codec/array_to_bytes/vlen.rs
  zarrs/src/array/codec/array_to_bytes/vlen/vlen_codec.rs
  zarrs/src/array/codec/array_to_bytes/vlen/vlen_partial_decoder.rs
  zarrs/src/array/codec/array_to_bytes/zfp.rs
  zarrs/src/array/codec/bytes_to_bytes/blosc.rs
  zarrs/src/array/codec/bytes_to_bytes/bz2.rs
  zarrs/src/array/codec/bytes_to_bytes/zlib.rs
  zarrs/src/array/data_type.rs
  zarrs/src/lib.rs
  zarrs/src/node.rs
  zarrs/tests/array_async.rs
  zarrs/tests/array_async_to_sync.rs
  zarrs/tests/array_partial_encode.rs
  zarrs/tests/array_sync.rs
  zarrs/tests/cities.rs
  zarrs/tests/zarr_python_numpy_time.rs
Labels: enhancement, breaking-changes
